config/routes.rb
Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq" # monitoring console

  get '/listings/:latitude/:longitude', to: 'listings#show', :as => :location_listing, :constraints => {:latitude => /\-?\d+(.\d+)?/, :longitude => /\-?\d+(.\d+)?/ }
  get '/listings/:latitude/:longitude/:id', to: 'houses#show',  :constraints => {:latitude => /\-?\d+(.\d+)?/, :longitude => /\-?\d+(.\d+)?/ }
  resources :listings, only: [:show, :new, :create, :post], param: :location do
      get '/:id' => 'houses#show', :as => :short_house
  end
  resources :favourites, only: [:index, :show, :create, :destroy ]
  
  root "listings#new"
  get "/help" => 'home#help', :as => :help

  get '*path' => 'home#invalid_route'

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  updated_at :datetime         not null
#

require 'nestoria'
#< ActiveRecord::Base
class Listing
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming

    #attr_reader :listings
    #attr_accessor :location

    #validates :location, presence: true

    #Initialize attributes
    #def initialize(attributes = {})
    #    attributes.each do |name, value|
    #        send("#{name}=", value)
    #    end
    #end

    #from tutorial, maybe not needed?
    def persisted?
        false
    end
    def initialize
        @@nestoria ||= MyNestoria.new
    end

    #Gets properties from nestoria
    def self.get_properties_with_total_number(location, page=1)
        @@nestoria ||= MyNestoria.new
        if(location && !location.blank?) then
            listings = []
            total_number = 0
            page.to_i.times do |p|
                l, total_number = @@nestoria.search_place(location, p+1)
                l.each do |listing|
                    listings << PropertyListing.new(listing)
                end
            end
            return listings, total_number
        else
            return listings, total_number
        end
    end
    def self.get_properties(location, page=1)
        self.get_properties_with_total_number(location, page).first
    end

    def self.get_house(location, id)
        return self.get_house_with_total_number(location, id).first
    end
    def self.get_house_with_total_number(location, id)
        listing = self.get_properties_with_total_number(location, id/20+1)
        return listing.first[id], listing.second
    end

    def self.get_location_with_total_number(lat, lon, page=1)
        @@nestoria ||= MyNestoria.new
        if !lat.blank? && !lon.blank? && lat.to_f && lon.to_f then
            listings = []
            total_number = 0
            page.to_i.times do |p|
                l, total_number = @@nestoria.search_location(lat, lon, p+1)
                l.each do |listing|
                    listings << PropertyListing.new(listing)
                end
            end
            return listings, total_number
        else
            return listings, total_number
        end
    end

    def self.get_location(lat, lon, page=1)
        self.get_location_with_total_number(lat,lon, page).first
    end
    def self.get_location_house_with_total_number(lat, lon, id)
        listing = self.get_location_with_total_number(lat, lon, id/20+1)
        return listing.first[id], listing.second
    end
    def self.get_location_house(lat, lon, id)
        return self.get_location_house_with_total_number(lat, lon, id).first
    end

    def self.get_total_number(location, page=1)
        @@nestoria ||= MyNestoria.new
        if location && page>=1 then
            listings, total_number = @@nestoria.search_place(location, page)
            return total_number
        end
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    def new
        @recentsearches = session[:recentsearches]
    end

    def show
        @page = params.has_key?(:page) ? params[:page] : 1
        if params[:location]
            @location = params[:location].blank? ? "" : params[:location].capitalize
            #Generate a valid url, chop the id (0) from the string
            @url = listing_short_house_path(@location, 0).chop
            @propertylistings, @total_number = Listing.get_properties_with_total_number(@location, @page)
        else 
            #search with lat/lon
            @latitude = params[:latitude]
            @longitude = params[:longitude]
            @location = params[:latitude]+"/".html_safe+params[:longitude]
            @url = location_listing_path(@latitude, @longitude)+"/"
            @propertylistings, @total_number = Listing.get_location_with_total_number(@latitude, @longitude, @page)
        end
        if @total_number.to_i > 0 then
                add_to_recent_searches(@location, @total_number)
            respond_to do |format|
                format.html 
                format.js 
            end
            else
                respond_to do |format| 
                    format.html {
                redirect_to root_path
                flash[:alert] = "There were no properties found for the given location."
                    }
                    format.js
                end
            end
    end

    def create
        if params["search"] then 
            if params["search"]["location_based"] && params["search"]["location_based"] == 'true' then
                if request.location && request.location.latitude && request.location.longitude then
                    redirect_to location_listing_url(latitude: request.location.latitude, longitude: request.location.longitude)
                else
                    flash[:alert] = "Was not able to determine your location, please try again later"
                    redirect_to root_path
                end
                return
            end
            if params["search"]["location"] && !params["search"]["location"].blank? then
                #redirect_to action: :show, location: params["search"]["location"] || ""
                redirect_to listing_url(params["search"]["location"])
            else
                redirect_to root_path
                flash[:alert] = "The location given was not recognised"
            end
        end
    end

    private

    #Can't add structs to session, so no advantages of using it here, create hash directly instead
    #Struct.new("Search", :name, :results)

    def add_to_recent_searches(name, results)
        unless session[:recentsearches].nil?
        session[:recentsearches].each do |search|
            if search['name'] == name.downcase
                session[:recentsearches].delete search
            end
        end
        end
        (session[:recentsearches] ||= []) <<{'name' => name.downcase, 'results' =>results}
        session[:recentsearches].uniq!
        #Leave only the last 4 searches
        session[:recentsearches] = session[:recentsearches].last(4)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/new.html.erb
<% provide(:title, "Search for Properties") %>
Use the form below to search for houses to buy. You can search by place-name, postcode, or click 'My location', to search in your current location!
<p>
<%= bootstrap_form_for(:search, url: listings_path) do |f| %>
    <div class="form-group">    
    <input placeholder="Enter location..." class="form-control" type="text" name="search[location]" id="search_location">
</div>
    <%= f.hidden_field :location_based, :value => false %>
    <%= f.submit 'Search' %>
    <%#= link_to "My location", location_listing_path , class: "btn btn-default"%>
    <%= f.submit "My location", :onclick => 'document.getElementById("search_location_based").value = true; this.form.submit()' , class: "btn btn-default"%>
<% end %>
</p>

    <% if @recentsearches then %>
<h2 class="recent-searches">Recent searches</h2>
<h4>Please select a location below:</h4>
<table class="recent-searches table-striped table table-hover table-clickeable">
        <%= render  partial: 'shared/recent_search', collection: @recentsearches.reverse[0..3] %>
</table>
    <% end %>

app/views/listings/show.html.erb
<% provide(:title, @propertylistings.count.to_s+" of "+@total_number.to_s+" matches") %>
<% if @propertylistings.any? %>
    <table class="table-striped table table-hover property-listing table-clickeable table-indexable" style="width:100%" id="property-listing">
        <% @propertylistings.each_with_index do |listing, counter| %>
        <%= render listing,  url: @url  %>
    <% end %>
    <% if @propertylistings.count < @total_number %>
    <tr id='load-more-row'><td class="center-align load-more" colspan=2 >
            Load more...<br>
            Results for <%= @location %>, showing <%= @propertylistings.count.to_s %> of <%= @total_number.to_s %> properties
    </td></tr>
<% end %>
</table>
<% else %>
    no location given
<% end %>

app/views/listings/show.js.erb
<% @propertylistings.last(20).each do |house| %>
    $('#property-listing tr:last').before(" <%= escape_javascript(render :partial => 'property_listings/property_listing', :locals => { :property_listing => house, :url => @url }  ) %> " );
<% end %>
$(".load-more")[0].innerHTML = "Load more...<br>Results for <%= @location %>, showing <%= @propertylistings.count.to_s %> of <%= @total_number.to_s %> properties";
$('.page-header h1').text("<%= @propertylistings.count.to_s+" of "+@total_number.to_s+" matches"%>")
<%# listing_url escapes forward slashes, so have to add ugly escaping here %>
history.replaceState(null, document.title, "<%= listing_url(0).chop+@location+"?page="+(@propertylistings.count/20).to_s %>");