config/routes.rb
Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq" # monitoring console

  get '/listings/:latitude/:longitude', to: 'listings#show', :as => :location_listing, :constraints => {:latitude => /\-?\d+(.\d+)?/, :longitude => /\-?\d+(.\d+)?/ }
  get '/listings/:latitude/:longitude/:id', to: 'houses#show',  :constraints => {:latitude => /\-?\d+(.\d+)?/, :longitude => /\-?\d+(.\d+)?/ }
  resources :listings, only: [:show, :new, :create, :post], param: :location do
      get '/:id' => 'houses#show', :as => :short_house
  end
  resources :favourites, only: [:index, :show, :create, :destroy ]
  
  root "listings#new"
  get "/help" => 'home#help', :as => :help

  get '*path' => 'home#invalid_route'

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
    layout "application_no_title"
  def show
      @id = params[:id].to_i
      #Proper REST-application and no database - so get Listing again...
      if params[:listing_location]
      @house = Listing.get_house(params[:listing_location], @id)
      else
      @house = Listing.get_location_house(params[:latitude], params[:longitude], @id)
      if @house.nil?
          redirect_to root_path
          flash[:alert] = "Could not show this house"
      end
      end
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form_add_favourite.html.erb
                            <%= form_for :favourite, url: favourites_path, remote: true do |f| %>
                            <%= f.hidden_field :price, :value => @house.price.to_s %>
                        <%= f.hidden_field :title, :value => @house.title %>
                        <%= f.hidden_field :summary, :value => @house.summary %>
                        <%= f.hidden_field :img_url, :value => @house.img_url %>
                        <%= f.hidden_field :thumb_url, :value => @house.thumb_url %>
                        <%= f.hidden_field :bedroom_number, :value => @house.bedroom_number.to_s %>
                        <%= f.hidden_field  :bathroom_number, :value => @house.bathroom_number.to_s %>
                        <%= f.hidden_field  :listing_location, :value => @listing_location %>
                        <%= f.button :submit do %>
                            <div class="favourite-icon">
                            <h1> <span class = "glyphicon glyphicon-heart-empty" aria-hidden="true"> </h1>
                            <% end %>
                            <% end %>

app/views/houses/_form_remove_favourite.html.erb
<%= form_for :favourite, url: favourite_path, remote: controller.class == HousesController ? true : false, method: :delete do |f| %>
    <%= f.hidden_field :title, :value => @house.title %>
<%= f.button :submit do %>

    <div class="favourite-icon">
    <h1> <span class = "glyphicon glyphicon-heart" aria-hidden="true"> </h1>
    <% end %>
    <% end %>

app/views/houses/show.html.erb
<% provide(:title, "£"+@house.price.to_s) %>
<%= render 'shared/house' %>