config/routes.rb
Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq" # monitoring console

  get '/listings/:latitude/:longitude', to: 'listings#show', :as => :location_listing, :constraints => {:latitude => /\-?\d+(.\d+)?/, :longitude => /\-?\d+(.\d+)?/ }
  get '/listings/:latitude/:longitude/:id', to: 'houses#show',  :constraints => {:latitude => /\-?\d+(.\d+)?/, :longitude => /\-?\d+(.\d+)?/ }
  resources :listings, only: [:show, :new, :create, :post], param: :location do
      get '/:id' => 'houses#show', :as => :short_house
  end
  resources :favourites, only: [:index, :show, :create, :destroy ]
  
  root "listings#new"
  get "/help" => 'home#help', :as => :help

  get '*path' => 'home#invalid_route'

end

app/views/shared/_add_danger.js.erb
$("#flash").html("<div class=\"alert alert-danger\"><%= message %></div>")
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 5000);

app/views/shared/_add_notice.js.erb
$("#flash").html("<div class=\"alert alert-info\"><%= message %></div>")
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 5000);

app/views/shared/_add_warning.js.erb
$("#flash").html("<div class=\"alert alert-warning\"><%= message %></div>")
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 5000);

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>© bbv Software Services AG <%= Time.zone.now.strftime("%Y") %></p>
</footer>

app/views/shared/_house.html.erb
<div class="row">
    <div class="col-md-4 col-xs-4">
        <h1> <%= "£"+@house.price.to_s %><h1> 
            </div>
            <div class="col-md-1 col-md-offset-7 col-xs-2 col-xs-offset-6 favourite-form">
                <% if house_is_favourite? @house.title  then %>
                    <%= render 'houses/form_remove_favourite' %>
                    <% else %>
                        <%= render 'houses/form_add_favourite' %>
                            <% end %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div id="house-title" class="col-md-12">
                            <h2><%= @house.title %></h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-xs-12 house-image">
                            <%= image_tag @house.img_url, width: '100%' %>
                        </div>
                        <div class="col-md-6">
                            <%= @house.bedroom_number.to_s+" Bedroom".pluralize(@house.bedroom_number) %>, <%= @house.bathroom_number.to_s+" Bathroom".pluralize(@house.bathroom_number) %> 
                            <p>
                            <div class="house-summary">
                                <%= @house.summary %>
                            </div>
                            </p>
                        </div>
                    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("PropertyCross", root_path, :class => "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%#= navbar_link_to("Home",
                           root_path,
                           :active_when => { :controller => "home" }) %>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">second action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Favourites", favourites_path %></li>
          <li><%= link_to "Help", help_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/shared/_page_header.erb
<div class="page-header">
  <% if content_for?(:title) %>
    <h1><%= content_for(:title) %></h1>
    <%= content_for(:page_subhead) %>
  <% else %>
    <h1>Untitled</h1>
    <p>Don’t forget to set <code>provide(:title)</code> for this view!</p>
  <% end %>
</div>

app/views/shared/_recent_search.html.erb
<% if recent_search["name"] && recent_search["results"] %>
<%# Can't use listing_path as it escapes forward slashes in location searches %>
    <tr data-url="/listings/<%= recent_search["name"].capitalize %>" >
    <td class="recent-search" >
        <%= recent_search["name"].capitalize %>
    </td>
    <td class="recent-search-number" >
        (<%= recent_search["results"].to_i %>)
    </td>
</tr>
<% end %>